### ISSUE TITLE
markup.php

### ISSUE THREAD

**Issue by sinagdev** [tcmulder/aquamin#1]
update `<?php echo $args[ '$content' ] ?? 'Dynamic Block'; ?>` to 
`<?php echo $args[ 'content' ] ?? 'Dynamic Block'; ?>`

**Comment by tcmulder** [comment]
Thanks @sinagdev! This'll be fixed in V4.1.0:

https://github.com/tcmulder/aquamin/blob/v4.1.0/includes/cli/templates/block-dynamic/markup.php
