### ISSUE TITLE
Reconsider add_editor_style.

### ISSUE THREAD

**Issue by tcmulder** [tcmulder/aquamin#53]
Using [add_editor_style](https://developer.wordpress.org/reference/functions/add_editor_style/) in includes/blocks.php causes @container querries to break, and it looks like there are many other issues. [Some use enquque_block_editor_assets](https://github.com/WordPress/gutenberg/issues/40444#issuecomment-1164422034) as a workaround: is that plausible, now that gutenberg is within an iframe?

Secondarily, does that allow Browsersync to work on the back-end...? 🤞

**Comment by tcmulder** [comment]
Note: this sorta works, except for some reason it won't load on the back-end over the Browsersync localhost proxy. I can't figure out why, which makes implementation feel risky.

It does however fix the original issue, allowing things like @container queries to work on the back-end. Except for localhost via Browsersync on the back-end, everything works just as I was hoping.

**Comment by tcmulder** [comment]
Got this working! It sorta bypasses add_editor_style for now while still using it... check out blocks.php for comments on how that works.

**Comment by strarsis** [comment]
New editor styles transformation approach using [PostCSS](https://github.com/WordPress/gutenberg/pull/49521) is now merged (many thanks @zaguiini)!
